#██████╗░░█████╗░███╗░░██╗██████╗░░█████╗░░██████╗██╗░░██╗░█████╗░██████╗░
#██╔══██╗██╔══██╗████╗░██║██╔══██╗██╔══██╗██╔════╝██║░░██║██╔══██╗██╔══██╗
#██████╔╝███████║██╔██╗██║██║░░██║███████║╚█████╗░███████║██║░░██║██████╔╝
#██╔═══╝░██╔══██║██║╚████║██║░░██║██╔══██║░╚═══██╗██╔══██║██║░░██║██╔═══╝░
#██║░░░░░██║░░██║██║░╚███║██████╔╝██║░░██║██████╔╝██║░░██║╚█████╔╝██║░░░░░
#╚═╝░░░░░╚═╝░░╚═╝╚═╝░░╚══╝╚═════╝░╚═╝░░╚═╝╚═════╝░╚═╝░░╚═╝░╚════╝░╚═╝░░░░░
#------------------------------------------------------------------------#
#                             Author: MrErrors                           #
#                              Verison: 1.0.1                            #
#------------------------------------------------------------------------#
Store-Menu-Items:
    Player-Balance:
        Display-Item:
            Material: player skull
            Name: "&8● <#1DE682>&l{displayname}"
            NBT: ""
            Lore:
            - '<#6A6A6A>Information'
            - ''
            - '  <#05E520>| <#EBEBEB>Sell Multiplier: <#05E520>{multiplier}x'
            - ''
            - '  <#27D2F0>| <#EBEBEB>Balance: <#27D2F0>${player_balance}'
    Exit-Menu:
        Display-Item:
            Material: spruce door
            Name: "&8● <#FF2626>&lCLOSE MENU"
            NBT: ""
            Lore:
            - '<#6A6A6A>Interactive Item'
            - ''
            - '<#FF2626>&l(!) <#FF2626>Click to close the shop!'
    Return-Menu:
        Display-Item:
            Material: spruce door
            Name: "&8● <#5BF027>&lMAIN STORE"
            NBT: ""
            Lore:
            - '<#6A6A6A>Interactive Item'
            - ''
            - '<#FF2626>&l(!) <#FF2626>Click to return to the main shop!'
    Back-Page:
        Display-Item:
            Material: gray dye
            Name: "&8● <#27D2F0>&lPREVIOUS PAGE"
            NBT: ''
    Next-Page:
        Display-Item:
            Material: gray dye
            Name: "&8● <#27D2F0>&lNEXT PAGE"
            NBT: ''
Shop-Lore:
    Lore:
    - '<#6A6A6A>Information'
    - ''
    - '  <#05E520>| <#EBEBEB>Sell Multiplier: <#05E520>{multiplier}x'
    - ''
    - '  <#27D2F0>| <#EBEBEB>Buy Price: <#27D2F0>${buy_price}'
    - ''
    - '  <#FF2626>| <#EBEBEB>Sell Price: <#FF2626>${sell_price}'
    - ''
    - '<#1DE682>&l(!) <#1DE682>Click to purchase or sell!'

Sell-Lore:
    Lore:
    - '<#6A6A6A>Information'
    - ''
    - '  <#05E520>| <#EBEBEB>Sell Multiplier: <#05E520>{multiplier}x'
    - ''
    - '  <#27D2F0>| <#EBEBEB>Sell Price: <#FF2626>${sell_price}'
    - ''
    - '  <#FF2626>| <#EBEBEB>Amount: <#FF2626>{item_amount}x'
    - ''
    - '<#1DE682>&l(!) <#1DE682>Click to sell!'

Buy-Lore:
    Lore:
    - '<#6A6A6A>Information'
    - ''
    - ''
    - '  <#27D2F0>| <#EBEBEB>Buy Price: <#27D2F0>${buy_price}'
    - ''
    - '  <#FF2626>| <#EBEBEB>Amount: <#FF2626>{item_amount}x'
    - ''
    - '<#1DE682>&l(!) <#1DE682>Click to purchase!'
Shops:
    Blocks:
        Display-Item:
            Material: player skull
            Slot: 13
            Name: "&8● <#5BF027>&lBUILDING BLOCKS &8| &f{shop_size} <#5BF027>Items"
            Lore:
            - "&7Search for you favorite items"
            - "&7to make your best builds!"
            - ''
            - "&6Blocks you can find here:"
            - "&8 ▶&f All stone types"
            - "&8 ▶&f All wood types"
            - "&8 ▶&f And much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGJmNmZiNDNjOWU0NWFjZTI0ZTc3YjY0YjYwNzVlYTMyZjQyMDYwM2IxNWFhYWQ3NTk3YWY3MDQ5YjkzNTM0NiJ9fX0'
    Colored:
        Display-Item:
            Material: player skull
            Slot: 20
            Name: "&8● <#E8E533>&lCOLORED BLOCKS &8| &f{shop_size} <#E8E533>Items"
            Lore:
            - "&7Make your builds stand out"
            - "&7with these blocks!"
            - ''
            - "&6Blocks you can find here:"
            - "&8 ▶ &fAll glass types"
            - "&8 ▶ &fAll wool types"
            - "&8 ▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjFkZTM5MGVmODZjYjNlYmZmYjgwZjBlOTY0NTU4NmJmZTA1MWYxMzY5YTMwN2NmYmE0ZjlmYWFiNzMwYjkwZiJ9fX0='
    Miscellaneous:
        Display-Item:
            Material: player skull
            Slot: 21
            Name: "&8● <#5f36e4>&lMISCELLANEOUS &8| &f{shop_size} <#5f36e4>Items"
            Lore:
            - "&7Usefull worktools and miscs"
            - "&7can be found here!"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fChests, Hoppers, Buckets,"
            - " &8▶ &fLeaves, Flowers, Torches"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjMyYzE0NzJhN2JjNjk3NWRlZDdjMGM1MTY5Njk1OWI4OWFmNjFiNzVhZTk1NGNjNDAzNmJjMzg0YjNiODMwMSJ9fX0='
    Spawner:
        Display-Item:
            Material: player skull
            Slot: 22
            Name: "&8● <#40748e>&lSPAWNERS &8| &f{shop_size} <#40748e>Items"
            Lore:
            - "&7Build your own farms and"
            - "&7start making money!"
            - ''
            - "&6Spawners you can find here:"
            - " &8▶ &fCow, Chicken, Zombie,"
            - " &8▶ &fSkeleton, Blaze, Golem"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTRmOGVmNTE0ZWQ2YmU3OWQzZThlZmJlMThlN2NiMzkxMjMyYmFkNDg4ZTNiMTk1NTJiN2ZmNGFiZTFmZjQ1ZCJ9fX0='
    RedStone:
        Display-Item:
            Material: player skull
            Slot: 23
            Name: "&8● <#FF2626>&lREDSTONE &8| &f{shop_size} <#FF2626>Items"
            Lore:
            - "&7Build your own farms and"
            - "&7start making money!"
            - ''
            - "&6Spawners you can find here:"
            - " &8▶ &fCow, Chicken, Zombie,"
            - " &8▶ &fSkeleton, Blaze, Golem"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGY4NGE0M2E0NThkYWI4ZDBmZTA1MDYyZTZiNDJlZGU3ZjI1MDRhNjQ5YzZjM2FiNjZjODY2NmUwYjgwNjlkNCJ9fX0='
    Minerals:
        Display-Item:
            Material: player skull
            Slot: 24
            Name: "&8● <#27D2F0>&lMINERALS &8| &f{shop_size} <#27D2F0>Items"
            Lore:
            - "&7Build your own farms and"
            - "&7start making money!"
            - ''
            - "&6Spawners you can find here:"
            - " &8▶ &fCow, Chicken, Zombie,"
            - " &8▶ &fSkeleton, Blaze, Golem"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2MxMWI0ODM3ZTc5M2RjYzA4OTU2YTY0OTMwZjc1ZWZhZWI1OTE0YTg3ZTFkYjg4OTRmNWRmNjAzMzBkMzE0NiJ9fX0='
    Farming:
        Display-Item:
            Material: player skull
            Slot: 29
            Name: "&8● <#1DE682>&lFARMING &8| &f{shop_size} <#1DE682>Items"
            Lore:
            - "&7Make your own garden and"
            - "&7sell what you harvest!"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fWheat, Seeds, Carrots,"
            - " &8▶&f Potatoes, Pumpkins, Melons"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTUwNmM4MjQ5YWZmOTc0YmQ1NDg1MTVmNjVlZjk4MWM4MDRhNTU5M2YxMmMyNDUxYWFiZTg2NzMxZTBjMWIxYiJ9fX0='
    Food:
        Display-Item:
            Material: player skull
            Slot: 30
            Name: "&8● <#EB3BFF>&lFOOD &8| &f{shop_size} <#EB3BFF>Items"
            Lore:
            - "&7Don't be hungry, fill"
            - "&7your appetite here!"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fAny meat,"
            - " &8▶ &fAny food"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGZhMWYxZmFjN2U5YjBhNjU3ZGQ4YzA0Yjk0NDc5YTk4YzM3M2UyZjQ2NDkxNmJiZTcwN2VmOTAwNDFkYzM5OSJ9fX0='
    Decorations:
        Display-Item:
            Material: player skull
            Slot: 31
            Name: "&8● <#1D94E6>&lDECORATIONS &8| &f{shop_size} <#1D94E6>Items"
            Lore:
            - "&7Best your enimies with"
            - "&7mighty potions!"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fBrewing equipment,"
            - " &8▶ &fAny potion"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGVmZjI5ZWE0NzFiMGRiZGIwZjhjZmZlNTIzZmZmZjZhYjAyYTVlZDI5OTBhYmFmMGUyYzYwNGQyMjdmMTA4NCJ9fX0='
    Combat:
        Display-Item:
            Material: player skull
            Slot: 32
            Name: "&8● &6&lCOMBAT &8| &f{shop_size} &6Items"
            Lore:
            - "&7Do you need PVP equipment"
            - "&7or some tools?"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fAny tool,"
            - " &8▶ &fAny armor"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmNkYzBmZWI3MDAxZTJjMTBmZDUwNjZlNTAxYjg3ZTNkNjQ3OTMwOTJiODVhNTBjODU2ZDk2MmY4YmU5MmM3OCJ9fX0='
    Mobdrops:
        Display-Item:
            Material: player skull
            Slot: 33
            Name: "&8● <#EB3BFF>&lMOB DROPS &8| &f{shop_size} <#EB3BFF>Items"
            Lore:
            - "&7Sell your earned mob drops"
            - "&7here to make serious cash!"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fPork, Beef, Bones, Blaze"
            - " &8▶ &fRods, Ender Pearls"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFkZDdlZTdkYzdmYmNiNWMxYWVlN2EyNTc5MTdmMDM0ZWViYTFlMDkzNzI3ZDcxMmRhYjBmYzM1ZmIwZTM4In19fQ=='
    Enchant:
        Display-Item:
            Material: player skull
            Slot: 40
            Name: "&8● <#E61D6F>&lENCHANTMENT"
            Lore:
            - "&7Don't be hungry, fill"
            - "&7your appetite here!"
            - ''
            - "&6Items you can find here:"
            - " &8▶ &fAny meat,"
            - " &8▶ &fAny food"
            - " &8▶ &fAnd much more!"
            - ''
            - "&eClick to browse category!"
            NBT: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2RjOTg1YTdhNjhjNTc0ZjY4M2MwYjg1OTUyMWZlYjNmYzNkMmZmYTA1ZmEwOWRiMGJhZTQ0YjhhYzI5YjM4NSJ9fX0='
            
Shop-Category-Sizes:
    Blocks: 0
    Colored: 0
    Miscellaneous: 0
    Spawner: 0
    RedStone: 0
    Minerals: 0
    Farming: 0
    Food: 0
    Decorations: 0
    Combat: 0
    Mobdrops: 0
